// Run with: node build-gallery.js
// Or add to your GitHub Actions / build step.
//
// Scans each subsystem image folder and writes gallery.config.js.

const fs   = require('fs');
const path = require('path');

const SUPPORTED = ['.jpg', '.jpeg', '.png', '.webp', '.gif', '.avif'];

const SUBSYSTEMS = [
  'droneConstruction',
  'droneControl',
  'attachments',
  'droneNetwork',
  'objectDetection',
];

const result = {};

for (const name of SUBSYSTEMS) {
  const dir = path.join(__dirname, 'assets/subsystems', name);
  if (!fs.existsSync(dir)) {
    fs.mkdirSync(dir, { recursive: true });
    console.log(`Created assets/subsystems/${name}/ — add images and re-run.`);
    result[name] = [];
    continue;
  }
  const files = fs.readdirSync(dir)
    .filter(f => SUPPORTED.includes(path.extname(f).toLowerCase()))
    .sort()
    .map(f => `assets/subsystems/${name}/${f}`);
  result[name] = files;
  console.log(`assets/subsystems/${name}/  →  ${files.length} image(s)`);
}

const output = `// Auto-generated by build-gallery.js — do not edit by hand.
// Re-run: node build-gallery.js
const GALLERY_IMAGES = ${JSON.stringify(result, null, 2)};
`;

fs.writeFileSync(path.join(__dirname, 'js/gallery.config.js'), output);
console.log('\njs/gallery.config.js updated.');
