const fs   = require('fs');
const path = require('path');
 
const SUPPORTED = ['.jpg', '.jpeg', '.png', '.webp', '.gif', '.avif'];
 
const ROOT = __dirname;
 
const SUBSYSTEMS = [
  'droneConstruction',
  'droneControl',
  'attachments',
  'droneNetwork',
  'objectDetection',
];
 
const result = {};
 
for (const name of SUBSYSTEMS) {
  const dir = path.join(ROOT, 'assets/subsystems', name);
  if (!fs.existsSync(dir)) {
    fs.mkdirSync(dir, { recursive: true });
    console.log(`Created assets/subsystems/${name}/ — add images and re-run.`);
    result[name] = [];
    continue;
  }
  const files = fs.readdirSync(dir)
    .filter(f => SUPPORTED.includes(path.extname(f).toLowerCase()))
    .sort()
    .map(f => `assets/subsystems/${name}/${f}`);
  result[name] = files;
  console.log(`assets/subsystems/${name}/  →  ${files.length} image(s)`);
}
 
const output = `// Auto-generated by build-gallery.js — do not edit by hand.
// Re-run: node js/build-gallery.js
const GALLERY_IMAGES = ${JSON.stringify(result, null, 2)};
`;
 
fs.writeFileSync(path.join(ROOT, 'gallery.config.js'), output);
console.log('\ngallery.config.js updated.');
