// Auto-generated by build-gallery.js — do not edit by hand.
// Re-run: node js/build-gallery.js
const GALLERY_IMAGES = {
  "droneConstruction": [
    "assets/subsystems/droneConstruction/drone1.webp",
    "assets/subsystems/droneConstruction/drone2.webp"
  ],
  "droneControl": [],
  "attachments": [],
  "droneNetwork": [],
  "objectDetection": []
};
