// Auto-generated by build-gallery.js — do not edit by hand.
// Re-run: node js/build-gallery.js
const GALLERY_IMAGES = {
  "droneConstruction": [
    "assets/subsystems/droneConstruction/drone1.webp",
    "assets/subsystems/droneConstruction/drone2.webp"
  ],
  "droneControl": [],
  "attachments": [
    "assets/subsystems/attachments/attachments_preview.png",
    "assets/subsystems/attachments/attachments_printed.png"
  ],
  "droneNetwork": [],
  "objectDetection": [
    "assets/subsystems/objectDetection/ai_device.png",
    "assets/subsystems/objectDetection/screenshot_one.png",
    "assets/subsystems/objectDetection/screenshot_two.png"
  ]
};
